[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.15.3", features = ["cuda"] }
host_guest_interface = { path = "../host_guest_interface" }
serde = "1.0"
