[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
#risc0-build = { version = "0.15.3" }
risc0-build = { path = "/home/user/risc_0/risc0/risc0/build" }

[package.metadata.risc0]
methods = ["guest"]
